### ISSUE TITLE
Does not support JDK v21+ in latest version of Android Studio Ladybug

### ISSUE THREAD

**Issue by nickdjones** [Mobile-Telematics/TelematicsApp-Android#34]
Gradle will not sync with the latest version of Android Studio Ladybug. To replicate, simply open the project and the Gradle sync will fail.

Workaround: Manually fix the JDK to version 17.

**Comment by telematicsgig** [comment]
Hey @nickdjones ,  we have updated the libriaries, now it supports the latest Android Studio. make sure you install all the latest patches.
